// TypeScript types for Supabase database schema
// This file will be auto-generated by Supabase CLI in production
// For now, we'll define types manually based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          agency_id: string | null;
          role: 'owner' | 'admin' | 'member';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          agency_id?: string | null;
          role?: 'owner' | 'admin' | 'member';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          agency_id?: string | null;
          role?: 'owner' | 'admin' | 'member';
          created_at?: string;
          updated_at?: string;
        };
      };
      agencies: {
        Row: {
          id: string;
          name: string;
          logo_url: string | null;
          brand_color: string | null;
          contact_name: string | null;
          contact_email: string | null;
          contact_phone: string | null;
          contact_photo: string | null;
          subscription_plan: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          logo_url?: string | null;
          brand_color?: string | null;
          contact_name?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          contact_photo?: string | null;
          subscription_plan?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          logo_url?: string | null;
          brand_color?: string | null;
          contact_name?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          contact_photo?: string | null;
          subscription_plan?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      clients: {
        Row: {
          id: string;
          agency_id: string;
          name: string;
          email: string;
          company: string | null;
          phone: string | null;
          notes: string | null;
          tags: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          agency_id: string;
          name: string;
          email: string;
          company?: string | null;
          phone?: string | null;
          notes?: string | null;
          tags?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          agency_id?: string;
          name?: string;
          email?: string;
          company?: string | null;
          phone?: string | null;
          notes?: string | null;
          tags?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      proposals: {
        Row: {
          id: string;
          agency_id: string;
          client_id: string;
          title: string;
          slug: string;
          status: 'draft' | 'sent' | 'viewed' | 'approved' | 'rejected';
          sent_at: string | null;
          viewed_at: string | null;
          approved_at: string | null;
          rejected_at: string | null;
          rejection_reason: string | null;
          valid_until: string | null;
          password_protected: boolean;
          password_hash: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          agency_id: string;
          client_id: string;
          title: string;
          slug?: string;
          status?: 'draft' | 'sent' | 'viewed' | 'approved' | 'rejected';
          sent_at?: string | null;
          viewed_at?: string | null;
          approved_at?: string | null;
          rejected_at?: string | null;
          rejection_reason?: string | null;
          valid_until?: string | null;
          password_protected?: boolean;
          password_hash?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          agency_id?: string;
          client_id?: string;
          title?: string;
          slug?: string;
          status?: 'draft' | 'sent' | 'viewed' | 'approved' | 'rejected';
          sent_at?: string | null;
          viewed_at?: string | null;
          approved_at?: string | null;
          rejected_at?: string | null;
          rejection_reason?: string | null;
          valid_until?: string | null;
          password_protected?: boolean;
          password_hash?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      proposal_sections: {
        Row: {
          id: string;
          proposal_id: string;
          title: string;
          order_index: number;
          elements: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          proposal_id: string;
          title: string;
          order_index: number;
          elements?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          proposal_id?: string;
          title?: string;
          order_index?: number;
          elements?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      templates: {
        Row: {
          id: string;
          agency_id: string;
          name: string;
          description: string | null;
          thumbnail_url: string | null;
          category: string | null;
          tags: string[] | null;
          content: Json;
          is_public: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          agency_id: string;
          name: string;
          description?: string | null;
          thumbnail_url?: string | null;
          category?: string | null;
          tags?: string[] | null;
          content?: Json;
          is_public?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          agency_id?: string;
          name?: string;
          description?: string | null;
          thumbnail_url?: string | null;
          category?: string | null;
          tags?: string[] | null;
          content?: Json;
          is_public?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      proposal_activities: {
        Row: {
          id: string;
          proposal_id: string;
          client_id: string | null;
          activity_type: 'viewed' | 'page_view' | 'download' | 'approved' | 'rejected';
          page_index: number | null;
          duration_seconds: number | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          proposal_id: string;
          client_id?: string | null;
          activity_type: 'viewed' | 'page_view' | 'download' | 'approved' | 'rejected';
          page_index?: number | null;
          duration_seconds?: number | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          proposal_id?: string;
          client_id?: string | null;
          activity_type?: 'viewed' | 'page_view' | 'download' | 'approved' | 'rejected';
          page_index?: number | null;
          duration_seconds?: number | null;
          metadata?: Json | null;
          created_at?: string;
        };
      };
      attachments: {
        Row: {
          id: string;
          proposal_id: string;
          file_name: string;
          file_size: number;
          file_type: string;
          storage_path: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          proposal_id: string;
          file_name: string;
          file_size: number;
          file_type: string;
          storage_path: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          proposal_id?: string;
          file_name?: string;
          file_size?: number;
          file_type?: string;
          storage_path?: string;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      user_role: 'owner' | 'admin' | 'member';
      proposal_status: 'draft' | 'sent' | 'viewed' | 'approved' | 'rejected';
      activity_type: 'viewed' | 'page_view' | 'download' | 'approved' | 'rejected';
    };
  };
}
